name: Deploy Angular App to EC2

on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy Angular app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Update system
            sudo apt update -y
            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed. Installing..."
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
              sudo chmod 666 /var/run/docker.sock

            fi
            # Clone the repository
            cd ~
            if [ ! -d "deployAngularApplication" ]; then
              git clone https://github.com/Shivambembey98/deployAngularApplication.git
            fi
            cd deployAngularApplication
            git pull origin main
            # Build and run the Docker container
            docker stop angular-calculator || true
            docker rm angular-calculator || true
            docker rmi angular-calculator || true
            docker build -t angular-calculator .
            docker run -d -p 8080:80 --name angular-calculator angular-calculator
